### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by Manyo-Dream** [Agr-Reader/Agr-Reader#10]
![S31008-23023224_com lowae agrreader](https://github.com/Agr-Reader/Agr-Reader/assets/114817669/59b2e4d2-2ca4-43ca-b23b-03758da92d54)
人民日报订阅乱码
http://www.people.com.cn/rss/world.xml

**Comment by Lowae** [comment]
乱码问题可升级到1.3.1版本解决
