### ISSUE TITLE
[Enhancement Label]RSS源添加及删除

### ISSUE THREAD

**Issue by FirstM1** [Agr-Reader/Agr-Reader#15]
1. 希望能增加网页版RSS管理器，通过网页来添加和删除RSS订阅源更加便捷。
2. 在软件内部对单个RSS订阅源添加左滑的3个菜单，分别是：撤销（为了恢复5秒内删除的订阅源），删除，归档。

**Comment by Lowae** [comment]
第一个功能已经超出目前功能范围了，因为我需要支持的不只有FreshRSS。
第二个功能建议可以
