### ISSUE TITLE
订阅源滑动的功能支持

### ISSUE THREAD

**Issue by zhusuner** [Agr-Reader/Agr-Reader#17]
订阅源右滑将订阅源的所有文章标记已读
订阅源左滑进入订阅源详情页面
![Screenshot_2023_1018_155335](https://github.com/Agr-Reader/Agr-Reader/assets/80241679/cf989582-3b2a-4c91-8dfe-16e7e021abb2)

**Comment by Lowae** [comment]
左右滑动已经支持已读或收藏
