### ISSUE TITLE
起始页自定义

### ISSUE THREAD

**Issue by zhusuner** [Agr-Reader/Agr-Reader#22]
●增加起始页自定义，可以自由设置信息流/今日未读/某个分组为起始页面。
●增加起始默认过滤条件自定义，自由设置起始过滤条件 为全部\未读\收藏\

**Comment by Lowae** [comment]
第二点已经满足，至于第一点暂时待定，如果有更多人反馈的话可以考虑加上

**Comment by Lowae** [comment]
1.4.2
