### ISSUE TITLE
无法登入 miniflux 的 Google reader 或者 Fever API 

### ISSUE THREAD

**Issue by gkeyes** [Agr-Reader/Agr-Reader#31]
用了几种方法都是显示无效凭证，用其他的软件可以正常登入

**Comment by Lowae** [comment]
可以邮件提供下供测试的账号

**Comment by zhoucheng8023** [comment]
同样问题，fever freshrss账户可以登录，greader提示无效凭证

**Comment by Lowae** [comment]
@zhoucheng8023 @gkeyes 方便邮件提供下测试用的账号信息吗？我这边测试下

**Comment by zhoucheng8023** [comment]
服务器搭在ipv6环境
地址http://qnap.505315435.xyz:1387/
账号test123
密码pass123
________________________________

**Comment by zhoucheng8023** [comment]
@Lowae 有邮箱吗,我通过邮箱发你

**Comment by Lowae** [comment]
@zhoucheng8023 Lowae@agrreader.xyz
