### ISSUE TITLE
webdav 配置问题

### ISSUE THREAD

**Issue by leodu0926** [Agr-Reader/Agr-Reader#32]
已入 pro
在配置 webdav 的时候明明已经输入正确的配置信息了，但是无法保存，保存完了之后始终说 webdav 未配置
![Screenshot_2024-02-26-18-47-12-18_59e278d8b7e3e7932c366090060c2620](https://github.com/Agr-Reader/Agr-Reader/assets/30851580/b2e24969-963a-4eed-a8d0-0f45a45a8803)

**Comment by Lowae** [comment]
可以邮件私发下配置信息，我这边看下

**Comment by leodu0926** [comment]
> 可以邮件私发下配置信息，我这边看下

麻烦你发个邮件给我，没找到你的邮箱，谢谢
 leodu0926@live.com
