### ISSUE TITLE
从RSS订阅链接中添加的订阅源拉取的文章数量有问题

### ISSUE THREAD

**Issue by taurus2146** [Agr-Reader/Agr-Reader#33]
我从右下角的从RSS订阅链接中添加 订阅源,基本所有订阅源的文章数量都有问题,基本都是10条左右,以下是我其中两个订阅源:
https://www.ruanyifeng.com/blog/atom.xml //只能拉取3条
https://weekly.tw93.fun/rss.xml //只能拉取10条
软件版本是2.28发布的1.6.1
手机系统是鸿蒙 版本是4.0.0.128

**Comment by Lowae** [comment]
你打开你发的链接看下就知道了，订阅源本身提供数量就这些

**Comment by taurus2146** [comment]
打开订阅源的链接的确是这样,但我用inoreader的时候它能拉取所有的,虽然默认的也只能拉部分,但是它可以选择是否拉取所有未读的(并不止订阅源链接提供的几个),这个后面会做这方面的优化吗?

**Comment by Lowae** [comment]
目前无法支持，因为这不是阅读器能提供的能力而是RSS服务的能力
