### ISSUE TITLE
大佬,能不能加个电脑版的阅读器 [Enhancement]

### ISSUE THREAD

**Issue by zenoprod** [Agr-Reader/Agr-Reader#36]
电脑工作的时候需要查看rss.
agr-reader是我目前看过最好的阅读器,希望能有一个电脑版本

#我尝试加标签了,好像点不了

**Comment by pu-007** [comment]
可以通过 WSA 使用

**Comment by Lowae** [comment]
暂时只能用模拟器比如wsa这类，其他平台还未规划
