### ISSUE TITLE
这个webdav似乎没有办法备份，我试过公网和内网，他能配置成功，但是无法备份，或者是我的操作不对，可以问一下大佬这个功能要怎样使用嘛，我试过在根目录，也试过自定义目录，但是始终没办法备份进去，因为这一个原因困扰了我，让我再三纠结要不要开Pro版，或是换个阅读器，我觉得这个阅读器是我用过的非常棒的，希望大佬能教一下

### ISSUE THREAD

**Issue by Mrxia** [Agr-Reader/Agr-Reader#37]
![IMG_20240409_234748.jpg](https://github.com/Agr-Reader/Agr-Reader/assets/101236069/ed8c757f-05ec-4141-8899-c24f0fadaa06)

**Comment by Lowae** [comment]
> ![IMG_20240409_234748.jpg](https://private-user-images.githubusercontent.com/101236069/320915250-ed8c757f-05ec-4141-8899-c24f0fadaa06.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTU3NDAsIm5iZiI6MTcxMzAxNTQ0MCwicGF0aCI6Ii8xMDEyMzYwNjkvMzIwOTE1MjUwLWVkOGM3NTdmLTA1ZWMtNDE0MS04ODk5LWMyNGYwZmFkYWEwNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxMzM3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjRkOWVkZjM0Yzg2NGVhODAwMmY4NTZjNDg1ODg4OTBmMmJhNDQ4NmE4MTBjZTYyNDU4M2Y4MTg4ODczZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5RdKkBMqC3cx_NlPooD1Hcpy9_Zr7mcOUmRcqEEzJaQ)

@Mrxia 如果有公网地址的话方便提供一下公网的webdav配置吗？邮件发我就行，我这边测试一下，因为Webdav条件有限测试场景不是很多。
Email: Lowae@agrreader.xyz

**Comment by Mrxia** [comment]
frp-2.dzkeji.xyz:7080&nbsp; xiaomi 123456地址是这个，他是frp内网穿透的http协议，我也试过tcp协议，好像都不行
&nbsp;


南&nbsp;墙。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月13日(星期六) 晚上9:37
收件人: ***@***.***&gt;; 
抄送: "南 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Agr-Reader/Agr-Reader] 这个webdav似乎没有办法备份，我试过公网和内网，他能配置成功，但是无法备份，或者是我的操作不对，可以问一下大佬这个功能要怎样使用嘛，我试过在根目录，也试过自定义目录，但是始终没办法备份进去，因为这一个原因困扰了我，让我再三纠�=9 3要不要开Pro版，或是换个阅读器，我觉得这个阅读器是我用过的非常棒的，希望大佬能教一下 (Issue #37)














  

  
@Mrxia 如果有公网地址的话方便提供一下公网的webdav配置吗？邮件发我就行，我这边测试一下，因为Webdav条件有限测试场景不是很多。
 Email: ***@***.***

**Comment by Mrxia** [comment]
已发送邮件
邮箱：[<a href="2452588468@dzkeji.xyz">发送电子邮件</a>](url)，请查收

**Comment by Lowae** [comment]
1.6.7 已修复
