### ISSUE TITLE
可不可以优化一下图片保存功能？

### ISSUE THREAD

**Issue by Taotao998** [Agr-Reader/Agr-Reader#48]
付费成为会员了我也还是不清楚怎么保存图片，可不可以增添一个长按弹出窗口询问是否保存，然后点击保存或点击空白取消的功能？一方面是到网页去了也不一定就支持保存，能方便的保存；另一方面加载网页有一个切换成本，很麻烦。

**Comment by Lowae** [comment]
点击图片后，有下载有个下载按钮就可以保存了
