### ISSUE TITLE
时间设置似乎有问题

### ISSUE THREAD

**Issue by oahcnauygnid** [Agr-Reader/Agr-Reader#49]
似乎时间设置的有问题，今日未读会出现下一天的情况，例如APP中显示的时间是12日00:30，点进去实际上是11日16:30，差了8小时，希望能修改

**Comment by Lowae** [comment]
这个世界取决于订阅源内文章本身发布时间，与app无关

**Comment by oahcnauygnid** [comment]
不是，我的意思app时间快了8个小时，app界面显示是14:00，但如果跳转浏览器打开，时间其实是6:00，差了8个小时。我猜测是时区导致的，但如果app使用的14:00是GMT时间，那北京时间应该是14:00+8=22:00，而不是6:00，不清楚是不是获取到的已经是北京时间了，然后以为是GMT又给+8了？
