### ISSUE TITLE
正文解析中图片与视频解析不出来

### ISSUE THREAD

**Issue by ranlychan** [Agr-Reader/Agr-Reader#6]
问题分类：bug
设备型号：Redmi K40
问题版本：1.2.0(20231002)-release
问题描述：在IT之家的一篇文章https://www.ithome.com/0/723/086.htm 中本来应该正常显示的视频与图片无法被agr reader解析，阅读模式下显示图片加载失败的图标。下面共有三副截图，其中第一与第二幅为阅读模式下无法正常显示图片的样子，第三幅是原始网页的正常显示状况。

![Screenshot_2023-10-05-09-56-02-560_com lowae agrreader](https://github.com/Agr-Reader/Agr-Reader/assets/56482592/d559636c-6617-4342-81c3-7271aa13522d)
![Screenshot_2023-10-05-09-59-59-694_com lowae agrreader](https://github.com/Agr-Reader/Agr-Reader/assets/56482592/12810444-6fdd-47f4-a836-360217b035a6)
![Screenshot_2023-10-05-09-59-19-077_com lowae agrreader](https://github.com/Agr-Reader/Agr-Reader/assets/56482592/d3760890-d72f-4fc5-bd95-c1334095eed2)

**Comment by Lowae** [comment]
图片加载不出来的问题已经修复，但是视频解析不了这个暂时没办法解决
